run:
  tests: true
  skip-dirs:
    - vendor
linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gofmt
    - goimports
    - gosimple
    - unused
    - structcheck
    - deadcode
issues:
  exclude-use-default: false
output:
  format: colored-line-number
