name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up Go
        uses: actions/setup-go@v5.4.0
        with:
          go-version: '1.23'
      - name: Cache Go modules
        uses: actions/cache@v4.2.3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Validate format
        run: go fmt ./...
      - name: Run vet
        run: go vet ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          version: v2.1.0
      - name: Test
        run: go test ./... -v -race -coverprofile=coverage.out
      - name: Benchmark
        run: go test ./... -bench=. -benchmem -timeout 30s
      - name: Upload coverage report
        uses: actions/upload-artifact@v4.6.2
        with:
          name: coverage-report
          path: coverage.out
      - name: Upload to Codecov
        uses: codecov/codecov-action@v5.4.2
        with:
          files: coverage.out
